services:
  web:
    build:
      context: .
      target: prod
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod
      DEBUG: "False"
    depends_on:
      redis:
        condition: service_healthy
    expose:
      - "8000"
    restart: unless-stopped
    command: >
      uvicorn config.asgi:application
      --host 0.0.0.0
      --port 8000
      --workers 2

  celery_worker:
    build:
      context: .
      target: prod
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod
      DEBUG: "False"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    command: celery -A config.celery_app worker -l info

  celery_beat:
    build:
      context: .
      target: prod
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod
      DEBUG: "False"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    command: celery -A config.celery_app beat -l info

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 30
      start_period: 2s

volumes: {}
