# Generated by Django 6.0 on 2026-01-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='A brief summary of who you are', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.CharField(blank=True, help_text='Your personal website or Facebook/Instagram profile', max_length=200),
        ),
    ]
