# Generated by Django 6.0 on 2026-01-11 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes Count'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['likes_count'], name='posts_likes_c_1d1075_idx'),
        ),
    ]
